hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/

spring:
  rabbitmq:
    host: rabbitmq

#security:
#  oauth2:
#    resource:
#      user-info-uri: http://localhost:5000/uaa/users/current

#spring:
#  rabbitmq:
#    host: localhost
