hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
  #maybe will need change this value on default=30 in production
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


#security:
#  oauth2:
#    resource:
#      user-info-uri: http://localhost:5000/uaa/users/current

#spring:
#  rabbitmq:
#    host: localhost
