version: '2'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
    expose:
      - 5672

  config:
    build: config
    ports:
      - 8888:8888

  registry:
    build: registry

  gateway:
    build: gateway

  monitoring:
    build: monitoring

  sleuth:
    build: sleuth

  account-service:
    build: account-service
    ports:
      - 9020:9020

  topic-service:
    build: topic-service
    ports:
      - 9010:9010

  auth-service:
    build: auth-service
    ports:
      - 5000:5000