version: '2'
services:
  gateway:
    env_file:
      - .env
    image: proshik/thinkclearly-gateway
    environment:
      CONFIG_SERVICE_HOST: $CONFIG_SERVICE_HOST
      CONFIG_SERVICE_PORT: $CONFIG_SERVICE_PORT
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      CONFIG_SERVICE_USERNAME: $CONFIG_SERVICE_USERNAME
    restart: always
    ports:
      - 80:4000
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  account-service:
    env_file:
      - .env
    image: proshik/thinkclearly-account-service
    environment:
      CONFIG_SERVICE_HOST: $CONFIG_SERVICE_HOST
      CONFIG_SERVICE_PORT: $CONFIG_SERVICE_PORT
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      CONFIG_SERVICE_USERNAME: $CONFIG_SERVICE_USERNAME
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  topic-service:
    env_file:
      - .env
    image: proshik/thinkclearly-topic-service
    environment:
      CONFIG_SERVICE_HOST: $CONFIG_SERVICE_HOST
      CONFIG_SERVICE_PORT: $CONFIG_SERVICE_PORT
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      CONFIG_SERVICE_USERNAME: $CONFIG_SERVICE_USERNAME
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

#  monitoring:
#    image: proshik/thinkclearly-monitoring
#    environment:
#      CONFIG_SERVICE_HOST: $CONFIG_SERVICE_HOST
#      CONFIG_SERVICE_PORT: $CONFIG_SERVICE_PORT
#      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
#      CONFIG_SERVICE_USERNAME: $CONFIG_SERVICE_USERNAME
#    restart: always
#    ports:
#      - 8787:8787
#      - 8989:8989
#    logging:
#      driver: gelf
#      options:
#        gelf-address: $LOG_GELF_ADDRESS

#  sleuth:
#    image: proshik/thinkclearly-sleuth
#    environment:
#      CONFIG_SERVICE_HOST: $CONFIG_SERVICE_HOST
#      CONFIG_SERVICE_PORT: $CONFIG_SERVICE_PORT
#      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
#      CONFIG_SERVICE_USERNAME: $CONFIG_SERVICE_USERNAME
#    restart: always
#    ports:
#      - 9411:9411
#    logging:
#      driver: gelf
#      options:
#        gelf-address: $LOG_GELF_ADDRESS