version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_HOST: $RABBITMQ_HOST
      RABBITMQ_PASSWORD: $RABBITMQ_PASSWORD
      RABBITMQ_USERNAME: $RABBITMQ_USERNAME
    restart: always
    ports:
      - 15672:15672
    expose:
      - 5672

  postgresql:
    build: postgres-init
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=$POSTGRES_USERNAME
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD

  config:
    image: proshik/config-server
    environment:
      CONFIG_SERVICE_PORT: $CONFIG_SERVICE_PORT
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      CONFIG_SERVICE_USERNAME: $CONFIG_SERVICE_USERNAME
      CONFIG_SERVICE_CSV_CONFIG_REPO_URL: $CONFIG_SERVICE_CSV_CONFIG_REPO_URL
      CONFIG_SERVICE_POSTFIX_APPLICATION: $CONFIG_SERVICE_POSTFIX_APPLICATION
    restart: always
    expose:
      - $CONFIG_SERVICE_PORT

  registry:
    image: proshik/registry-server
    environment:
      REGISTRY_SERVICE_PORT: $REGISTRY_SERVICE_PORT
    restart: always
    ports:
      - $REGISTRY_SERVICE_PORT:$REGISTRY_SERVICE_PORT
    expose:
      - $REGISTRY_SERVICE_PORT

  gateway:
    build: gateway
    env_file:
      - .env
    environment:
      CONFIG_SERVICE_HOST: $CONFIG_SERVICE_HOST
      CONFIG_SERVICE_PORT: $CONFIG_SERVICE_PORT
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      CONFIG_SERVICE_USERNAME: $CONFIG_SERVICE_USERNAME
      CONFIGURATION_ENVIRONMENT: $CONFIGURATION_ENVIRONMENT
    restart: always
    links:
      - config
    ports:
      - 80:4000

  account-service:
    build: account-service
    env_file:
      - .env
    environment:
      CONFIG_SERVICE_HOST: $CONFIG_SERVICE_HOST
      CONFIG_SERVICE_PORT: $CONFIG_SERVICE_PORT
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      CONFIG_SERVICE_USERNAME: $CONFIG_SERVICE_USERNAME
      CONFIGURATION_ENVIRONMENT: $CONFIGURATION_ENVIRONMENT
    restart: always
    links:
      - config
      - postgresql
      - rabbitmq
      - auth-service
    ports:
      - 9020:9020

  topic-service:
    build: topic-service
    env_file:
      - .env
    environment:
      CONFIG_SERVICE_HOST: $CONFIG_SERVICE_HOST
      CONFIG_SERVICE_PORT: $CONFIG_SERVICE_PORT
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      CONFIG_SERVICE_USERNAME: $CONFIG_SERVICE_USERNAME
      CONFIGURATION_ENVIRONMENT: $CONFIGURATION_ENVIRONMENT
    links:
      - config
      - postgresql
      - rabbitmq
      - auth-service
    restart: always
    ports:
      - 9010:9010

  auth-service:
    build: auth-service
    env_file:
      - .env
    environment:
      CONFIG_SERVICE_HOST: $CONFIG_SERVICE_HOST
      CONFIG_SERVICE_PORT: $CONFIG_SERVICE_PORT
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      CONFIG_SERVICE_USERNAME: $CONFIG_SERVICE_USERNAME
      CONFIGURATION_ENVIRONMENT: $CONFIGURATION_ENVIRONMENT
    restart: always
    links:
      - config
      - postgresql
      - rabbitmq
    ports:
      - 5000:5000

  monitoring:
    build: monitoring
    env_file:
      - .env
    environment:
      CONFIG_SERVICE_HOST: $CONFIG_SERVICE_HOST
      CONFIG_SERVICE_PORT: $CONFIG_SERVICE_PORT
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      CONFIG_SERVICE_USERNAME: $CONFIG_SERVICE_USERNAME
      CONFIGURATION_ENVIRONMENT: $CONFIGURATION_ENVIRONMENT
    restart: always
    links:
      - config
      - rabbitmq
    ports:
      - 8787:8787
      - 8989:8989

  sleuth:
    build: sleuth
    env_file:
      - .env
    environment:
      CONFIG_SERVICE_HOST: $CONFIG_SERVICE_HOST
      CONFIG_SERVICE_PORT: $CONFIG_SERVICE_PORT
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      CONFIG_SERVICE_USERNAME: $CONFIG_SERVICE_USERNAME
      CONFIGURATION_ENVIRONMENT: $CONFIGURATION_ENVIRONMENT
    restart: always
    links:
      - config
      - rabbitmq
    ports:
      - 9411:9411